# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a30d45a572d4c43ed80201f8f784eb6daa670dbdba178c245eac3bed4b9bfa846bfa420fea0191f4ed7402930599b1a71424316b79cfd589b5c0922973d5ed68

test:
  secret_key_base: dde3660bcc7edfeb23e4d1138393e8a040a4652d04d9757fad235d9ce2f7ba83dc61f3f5b65b958290cdd8dd5696630af2cd3bd8c171b1a7302b6d24b76ca69a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
